# Generated by Django 5.0.7 on 2024-12-26 14:39

import django.utils.timezone
import music.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_businessuser_album_artist_alter_song_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='release_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='song',
            name='duration',
            field=models.IntegerField(validators=[music.models.validate_positive]),
        ),
    ]
