# Generated by Django 5.0.7 on 2024-12-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_album_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessuser',
            name='thumbnail',
            field=models.ImageField(default='images/album/1.jpg', upload_to='images/'),
            preserve_default=False,
        ),
    ]
